title: romanroth.github.io
description: Blog and knowledge base.

name: &name "Roman Roth" # &name is a YAML anchor which can be *referenced later
github_username:  romanroth
domain: romanroth.github.io
url: https://romanroth.github.io

remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "neon"

plugins:
  - jekyll-feed
  - jekyll-include-cache

include: ["_pages"]

search                   : true # true, false (default)
search_full_content      : true # true, false (default)
search_provider          : lunr # lunr (default), algolia

# Site Author
author:
  name: *name # *name is a YAML reference pointing to the &anchor earlier
  avatar: "/assets/images/avatar.jpg"
  bio: "Currently studying computer science in Germany."
  location: "Germany"
  links:
    - label: "Github"
      url: "https://github.com/romanroth"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      show_date: true
      date_format: "%Y-%m-%d"
      read_time: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
